package Entity;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

public class Execute_ptClient
{
  @WebServiceRef
  private static UserAuthService userAuthService;

  public Users getLogin(String username, String password)
  {
    userAuthService = new UserAuthService();
    Execute_ptt execute_ptt = userAuthService.getExecute_pt();
    // Add your code to call the desired methods.
    UserAuthDBAdapterSelectUsernamePassword WSParams = new UserAuthDBAdapterSelectUsernamePassword();
    
    WSParams.setUsername("test");
    WSParams.setPassword("test");
    
    Users response = execute_ptt.execute(WSParams);
    return response;
  }
}
