package Entity.ApproveAfspraak;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

@WebServiceClient(wsdlLocation="http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/ApproveAfspraakService?WSDL",
  targetNamespace="http://oracle.com/sca/soapservice/epd/EPDSOA/ApproveAfspraakService",
  name="ApproveAfspraakService")
public class ApproveAfspraakService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("Entity.ApproveAfspraak.ApproveAfspraakService");
      URL baseUrl = ApproveAfspraakService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ApproveAfspraakService.class.getResource("http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/ApproveAfspraakService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/ApproveAfspraakService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/ApproveAfspraakService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/ApproveAfspraakService?WSDL",
          e);
    }
  }

  public ApproveAfspraakService()
  {
    super(wsdlLocationURL,
          new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/ApproveAfspraakService",
                    "ApproveAfspraakService"));
  }

  public ApproveAfspraakService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public Entity.ApproveAfspraak.Execute_ptt getExecute_pt()
  {
    return (Entity.ApproveAfspraak.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/ApproveAfspraakService",
                                                                        "execute_pt"),
                                                              Entity.ApproveAfspraak.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public Entity.ApproveAfspraak.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (Entity.ApproveAfspraak.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/ApproveAfspraakService",
                                                                        "execute_pt"),
                                                              Entity.ApproveAfspraak.Execute_ptt.class,
                                                              features);
  }
}
