package Entity.JAXWS;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

@WebServiceClient(wsdlLocation="http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/LoginService?WSDL",
  targetNamespace="http://oracle.com/sca/soapservice/epd/EPDSOA/LoginService",
  name="LoginService")
public class LoginService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("Entity.JAXWS.LoginService");
      URL baseUrl = LoginService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            LoginService.class.getResource("http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/LoginService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/LoginService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/LoginService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/LoginService?WSDL",
          e);
    }
  }

  public LoginService()
  {
    super(wsdlLocationURL,
          new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/LoginService",
                    "LoginService"));
  }

  public LoginService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public Entity.JAXWS.Execute_ptt getExecute_pt()
  {
    return (Entity.JAXWS.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/LoginService",
                                                              "execute_pt"),
                                                    Entity.JAXWS.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public Entity.JAXWS.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (Entity.JAXWS.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/epd/EPDSOA/LoginService",
                                                              "execute_pt"),
                                                    Entity.JAXWS.Execute_ptt.class,
                                                    features);
  }
}
