<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="InsertAfspraakService"
     targetNamespace="http://oracle.com/sca/soapservice/epd/EPDSOA/InsertAfspraakService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://www.example.org"
     xmlns:tns="http://oracle.com/sca/soapservice/epd/EPDSOA/InsertAfspraakService"
    >
    <wsdl:documentation>
        <abstractWSDL>http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1!1.0/InsertAfspraakService.wsdl</abstractWSDL>
    </wsdl:documentation>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.example.org" schemaLocation="InsertAfspraak.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:Afspraak"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_pttBinding" type="tns:execute_ptt">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="execute"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://oracle.com/sca/soapservice/epd/EPDSOA/InsertAfspraakService"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="InsertAfspraakService">
        <wsdl:port name="execute_pt" binding="tns:execute_pttBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://ORACLE-SOA-SUITE:8001/soa-infra/services/default/Project1/InsertAfspraakService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
